### ISSUE TITLE
Multiple revision of one component in the AppConfig

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#110]
```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: my-app-deployment
  annotations:
    version: v1.0.0
    description: "Description of this deployment"
spec:
  components:
    - revisionName: example-component-1
      traits:
        - apiversion:core.oam.dev/v1alpha2
          kind: ManualScaler
          spec:
            replicaCount: 3
    - revisionName: example-component-2
      traits:
        - apiversion:core.oam.dev/v1alpha2
          kind: ManualScaler
          spec:
            replicaCount: 2
```

In this example, revision  ` example-component-1` and `example-component-2` are of the same component.

Add this case into revision proposal, and make sure this case work.

**Comment by captainroy-hy** [comment]
It comes across with below confusing scenario. 
Here's the schematic of a Component
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
        - name: wordpress
          image: wordpress:php7.2
  parameters:
    - name: instance-name
      required: true
      fieldPaths:
        - metadata.name # this param allows to override the name of workload obj
```
And the appConfig contains two revision of one component but they are assigned the same workload name.
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
    - revisionName: example-component-bs48sm18d3b8dpjvdab0
      parameterValues:
        - name: instance-name
          value: same-workload-name
    - revisionName: example-component-bs4l2f98d3b8dpjvdabg
      parameterValues:
        - name: instance-name
          value: same-workload-name
```
The deployment result is that there's only one ContainerizedWorkload object created, and in each round of reconciling, one more pod is being created but terminated immediately.
```shell
$ kubectl get pods
NAME                                  READY   STATUS        RESTARTS   AGE
same-workload-name-7b9ff9bb67-ztcsz   0/1     Terminating   0          15s
same-workload-name-854c9cf678-94wv6   1/1     Running       0          2m24s
```
---
Current versioning implementation creates a  workload with specified revision through setting workload's `metadata.name` as `revisionName` or `componentName`, but Component Parameter or any other way that can modify workload's name may lead to unpredictable result on versioning mechanism.

**Comment by wonderflow** [comment]
The essential problem here is we can't specify parameters especially instance name if we want to use workload revision. @captainroy-hy

**Comment by captainroy-hy** [comment]
> The essential problem here is we can't specify parameters especially instance name if we want to use workload revision. @captainroy-hy

Yes, and nor fixing workload name in Component schematic like below, even maybe no one would like to do this...
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: fixed-name
    spec:
...
```
