### ISSUE TITLE
How do we handle target reference fields and labels? 

### ISSUE THREAD

**Issue by resouer** [crossplane/oam-kubernetes-runtime#136]
In OAM, the target reference fields or label selectors do not make a lot sense. For example, consider these traits below:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
```

```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
```

All these label `selector` and `scaleTargetRef` can be generated by OAM runtime since OAM clearly know which workload it bound to (AWS folks call this "intention driven").

**So the question is can we do and will we do this for users?**

Several approaches if we want to do this:
1. Write a CRD controller to generate them. For example, a trait named `Expose`.
2. Enumerate k8s resources and handle them one by one.
3. Placeholder on the object (not good for oam-runtime but should work for app engine's template object). For example: 
    ```yaml  
    scaleTargetRef: \$(OAM_WORKLOAD_REF) # or defined in parameters list
    ...
    podSelector:
      matchLabels: \$(OAM_WORKLOAD_LABELS) # or defined in parameters list
    ```

Any thoughts? @hongchaodeng @wonderflow @zzxwill @ryanzhang-oss
