### ISSUE TITLE
[Question]Can different workloads be selected？

### ISSUE THREAD

**Issue by wenxinnnnn** [crossplane/oam-kubernetes-runtime#149]
In order to meet the needs of each service of our microservices to mount the sidecar of consul-client.

I tried to develop a **SidecarSetWorkload** for the [catalog](https://github.com/oam-dev/catalog), but I needed a differentiated choice of pod to mount the sidecar. I saw a related issue: #136， Do I have any other solutions?

```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: myService-Sidecar
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: SidecarSetWorkload
    metadata:
      name: sonsul-client-sidecar
    spec:
      selector:
        matchLabels:
          app: myService
      containers:
       - name: consul
         image: consul:1.3.1
         args:
         - "agent"
         - "-data-dir=/consul/data"
         - "-advertise=$(PODIP)"
         - "-client=0.0.0.0"
         - "-node=activity-system-$(PODIP)"
         - "-retry-join=consul-service"
         - "-domain=cluster.local"
         - "-disable-host-node-id"
         ...
    parameters:
        ...
```
