### ISSUE TITLE
Resource Dependency to support appending array of unstructured types

### ISSUE THREAD

**Issue by hongchaodeng** [crossplane/oam-kubernetes-runtime#167]
Have talked offline to some users and get the following feedback:

In the [Cloud logging setup](https://help.aliyun.com/document_detail/131598.html?spm=a2c4g.11174283.6.1009.103d2ceeD8wee2), it requires to pass `[]v1.EnvVar`, `[]v1.Volume`, `[]v1.VolumeMount` as the parameters:

```yaml
      containers:
      - image: alpine
        imagePullPolicy: Always
        args:
        - ping
        - 127.0.XX.XX
        name: alpine
        env:
        - name: aliyun_logs_project
          value: k8s-xxx
        - name: aliyun_logs_machinegroup
          value: k8s-group-app-alpine
        - name: aliyun_logs_log-stdout
          value: stdout
        - name: aliyun_logs_test-file
          value: /log/*.log
        - name: aliyun_logs_test-stdout_ttl
          value: "7"
        - name: aliyun_logs_test-stdout_shard
          value: "2"
        volumeMounts:
        - name: volume-sls
          mountPath: /log
      volumes:
      - name: volumn-sls
        emptyDir: {}
```

However, the current implementation doesn't support such array types yet.
