### ISSUE TITLE
[Feature] Proper defaulting for metadata of workload

### ISSUE THREAD

**Issue by resouer** [crossplane/oam-kubernetes-runtime#174]
**Is your feature request related to a problem? Please describe.**

Ref: https://github.com/crossplane/oam-kubernetes-runtime/issues/136

OAM runtime should automatically generate labels for Workload (ref: [k8s recommend labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)), I'd propose three standard labels below:

```yaml
workload.oam.dev/name: <same with metadata.name above>
workload.oam.dev/revision: <revision number>
workload.oam.dev/component: <component name this workload belongs to>
```
For example:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    workload.oam.dev/name: <same with metadata.name above>
    workload.oam.dev/revision: <revision number>
    workload.oam.dev/component: <component name this workload belongs to>
spec:
  replicas: 3
  # skip ... labelSelector and label for pod section
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

**Comment by ryanzhang-oss** [comment]
> ```yaml
> workload.oam.dev/name: <same with workload's metadata.name>
> ```

Why do we need this when the name is already in the meta?


> ```yaml
> workload.oam.dev/revision: <revision number>
> ```
What revision is this? It looks like it's not the component revision number.

**Comment by resouer** [comment]
@ryanzhang-oss These labels are all component's info, not workload, I've updated the label key and example.

**Comment by wonderflow** [comment]
This is an important issue, with this label, **trait can find underlying pods easily**.

It's helpful at least for below two cases:

* ingress/service/traffic trait can easily route their traffic to pods with the information of OAM AppConfig/Component.
* log/metrics trait can easily find which pods need to gather logs or metrics  by OAM AppConfig.

What's more, any trait can rely on K8s `label selector` ability to find underlying resource through abstraction layer.

Besides these to labes:

```
component.oam.dev/name: <component's metadata.name>
component.oam.dev/revision: <revision number of the component>
```

I propose we add one more to indicate which AppConfig instance it is：

```
appconfig.oam.dev/name: <appconfig's metadata.name>
```

**Comment by resouer** [comment]
Not sure how about `app.oam.dev/name: <appconfig's metadata.name>`?

Others, all agree.

**Comment by resouer** [comment]
Some other optional but valuable labels:

```yaml
workload.oam.dev/type: server|worker|task
workload.oam.dev/replicable: true
workload.oam.dev/podspecable: true
```

These labels are important for `appliesTo` work properly.
