### ISSUE TITLE
[BUG] Cannot apply all components in one AppConfig

### ISSUE THREAD

**Issue by captainroy-hy** [crossplane/oam-kubernetes-runtime#187]
**Describe the bug**

This [return ](https://github.com/crossplane/oam-kubernetes-runtime/blob/2ba1df7019edcfa7952c0dfae87318c365aae55a/pkg/controller/v1alpha2/applicationconfiguration/apply.go#L121) control will break the loop of applying a slice of workloads. If there are a number of components in one AppConfig and someone of them has available `scopes`, then only parts of the components can be applied successfully.

**To Reproduce**

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
    - componentName: exp-comp-deploy
      scopes: 
        - scopeRef:
            apiVersion: core.oam.dev/v1alpha2
            kind: HealthScope
            name: example-health-scope
    - componentName: exp-comp-deploy-x
      scopes: 
        - scopeRef:
            apiVersion: core.oam.dev/v1alpha2
            kind: HealthScope
            name: example-health-scope
    - componentName: exp-comp-cw 
      scopes: 
        - scopeRef:
            apiVersion: core.oam.dev/v1alpha2
            kind: HealthScope
            name: example-health-scope

```
