### ISSUE TITLE
[BUG] Can't find workloadDefinition is name was not match pattern <puraral-kind>.<resource-group>

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#207]
**Describe the bug**

In #195 and #198 , we have created some workload definition have custom name.

When working with Definition like [this](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/examples/typed-component/definitions.yaml#L4). The controller can't work, it says can't find workloadDefinition as we don't follow the old convention that definition name will always equal to CRD name which match the pattern `<puraral-kind>.<resource-group>`

**Comment by zzxwill** [comment]
This happens when WorkloadDefinition's name doesn't follow the convention of `<puraral-kind>.<resource-group>`. For example.
- WorkloadDefinition with name `web-service`
```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  annotations:
    definition.oam.dev/name: web-service
  name: web-service
spec:
  definitionRef:
    name: containerizedworkloads.core.oam.dev
  childResourceKinds:
    - apiVersion: apps/v1
      kind: Deployment
    - apiVersion: v1
      kind: Service
```

- component
```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      annotations:
        definition.oam.dev/name: web-service
    spec:
      containers:
        - name: wordpress
          image: wordpress:4.6.1-apache
          ports:
            - containerPort: 80
              name: wordpress
          env:
            - name: TEST_ENV
              value: test
  parameters:
    - name: instance-name
      fieldPaths:
        - metadata.name
    - name: image
      fieldPaths:
        - spec.containers[0].image
```

- ApplicationConfiguration
```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
    - componentName: example-component
      parameterValues:
        - name: image
          value: wordpress:php7.2
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            metadata:
              name: example-appconfig-trait
            spec:
              replicaCount: 3
```

After these manifest are applied, it will hit the issue as below.
```
  Warning  failed to fetch workload child resources  4s (x2 over 5s)  ManualScalarTrait                          WorkloadDefinition.core.oam.dev "containerizedworkloads.core.oam.dev" not found
```

**Comment by zzxwill** [comment]
# Solution intro
After discussion with @wonderflow , here is the solution of draft PR #208 

For those WorkloadDefinitions whose name doesn't follow the pattern `<puraral-kind>.<resource-group>`, it's required them to add `metadata.annotations.definition.oam.dev/name` to set the name of the WorkloadDefintion, so is for Workload in Component manifest.
```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  annotations:
    definition.oam.dev/name: web-service
  name: web-service
```

```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      annotations:
        definition.oam.dev/name: web-service
```

When reconciling, OAM runtime will first check whether there is a filed `metadata.annotations.definition.oam.dev/name`, if yes, it will get the CRD name by it, or it will keep the previous way to retrieve the CRD name.

# Solution comparison

Compared with the solution describe in #195 which required to add `spec.workload.type`, both can work, but this one is simpler. 
`spec.workload` is type `runtime.RawExtension` which need unmarshal first to fetch the WorkloadDefinition, while `metadata.annotations.definition.oam.dev/name` could be directly retrieved.
