### ISSUE TITLE
[Feature] add apiversion and kind into Definition

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#210]
In vela we write definition like this:

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: metricstraits.standard.oam.dev
  namespace: default
  annotations:
    definition.oam.dev/apiVersion: standard.oam.dev/v1alpha1
    definition.oam.dev/kind: MetricsTrait
spec:
  appliesToWorkloads:
    - containerizedworkloads.core.oam.dev
    - clonesetworkloads.apps.kruise.io
  definitionRef:
    name: metricstraits.standard.oam.dev
  workloadRefPath: spec.workloadRef
```

We need to use annotations to tell which GVK the definition is pointing to, this is designed to be fixed by field `definitionRef`.

The original design is that we assume there will always be only one version for one existing CRD, but we can't actually.

Currently we use the first version found: https://github.com/crossplane/oam-kubernetes-runtime/blob/master/pkg/webhook/v1alpha2/component/mutating_handler.go#L120

This may not correct.

So we prepare to add below:

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: metricstraits.standard.oam.dev
  namespace: default
spec:
  appliesToWorkloads:
    - containerizedworkloads.core.oam.dev
    - clonesetworkloads.apps.kruise.io
  definitionRef:
    name: metricstraits.standard.oam.dev
    apiVersion: standard.oam.dev/v1alpha1
    kind: MetricsTrait
  workloadRefPath: spec.workloadRef
```

This also works for WorkloadDefinition.

# Alternatives

If we only add a version into DefinitionRef, this also works, we can [discovery resources by group and version using discovery client](https://github.com/kubernetes/client-go/blob/master/discovery/discovery_client.go#L90) 

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: metricstraits.standard.oam.dev
  namespace: default
spec:
  appliesToWorkloads:
    - containerizedworkloads.core.oam.dev
    - clonesetworkloads.apps.kruise.io
  definitionRef:
    name: metricstraits.standard.oam.dev
    version: v1alpha1
  workloadRefPath: spec.workloadRef
```
