### ISSUE TITLE
healthscope apply failed[BUG]

### ISSUE THREAD

**Issue by xishengcai** [crossplane/oam-kubernetes-runtime#231]
**Describe the bug**
healthscope can't pave， will report error: no fields
```
59s         Warning   CannotApplyComponents    applicationconfiguration/example-appconfig                          cannot find scope workloadRef "core.oam.dev/v1alpha2" "HealthScope" "example-health-scope" with workloadRefsPath "spec.workloadRefs": spec: no such field
```
if value, err := fieldpath.Pave(s.UnstructuredContent()).GetValue(workloadRefsPath); err == nil

**To Reproduce**
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: ScopeDefinition
metadata:
  name: healthscopes.core.oam.dev
spec:
  allowComponentOverlap: true
  workloadRefsPath: spec.workloadRefs
  definitionRef:
    name: healthscopes.core.oam.dev
---
apiVersion: core.oam.dev/v1alpha2
kind: HealthScope
metadata:
  name: example-health-scope
```
```
....
     scopes:
        - scopeRef:
            apiVersion: core.oam.dev/v1alpha2
            kind: HealthScope
            name: example-health-scope

```

**Comment by captainroy-hy** [comment]
Miss a required field when creating a HealthScope
```
apiVersion: core.oam.dev/v1alpha2
kind: HealthScope
metadata:
  name: example-health-scope
spec:
  workloadRefs: [] # <-- this field is required
```
