### ISSUE TITLE
[Proposal] Add a 'podSpecPath' field in WorkloadDefinition

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#233]
We have discussed a lot and finally conclude to add labels like [`workload.oam.dev/podspecable`](https://github.com/oam-dev/spec/blob/master/4.workload_definitions.md#labels) to indicate the workload will contain 'podSpec' in it's spec.

But it's hard to know which field is podSpec, so I propose we add a 'podSpecPath' field in WorkloadDefinition.

By defualt, if `workload.oam.dev/podspecable: true` label is set but `podSpecPath` not, we may go to `spec.template` to find 'podTemplate', and get 'podSpec' in `spec.template.spec`.

If this field is set like below, we will directly regard path specified in `podSpecPath` as `podSpec` path, in this example, it's `spec.podSpec`

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webservice
  labels:
     workload.oam.dev/podspecable: true
  annotations:
    definition.oam.dev/apiVersion: "standard.oam.dev/v1alpha1"
    definition.oam.dev/kind: "PodSpecWorkload"
spec:
  podSpecPath: "spec.podSpec"
  definitionRef:
    name: podspecworkloads.standard.oam.dev
  childResourceKinds:
    - apiVersion: apps/v1
      kind: Deployment
    - apiVersion: v1
      kind: Service
```

This is also needed to fix https://github.com/oam-dev/kubevela/issues/354

**Comment by resouer** [comment]
+1, I also noticed this issue for a while: `podspecable` doesn't mean `spec.template.spec` exists.

**Comment by hongchaodeng** [comment]
+1. 
Shouldn't it be podSpecFieldPath ?

**Comment by ryanzhang-oss** [comment]
This reminds me of the `workloadRefPath` which caused some problems when it is not presented (https://github.com/crossplane/oam-kubernetes-runtime/pull/232). I know this will be an optional field, I wonder what's the exact behavior when it is not present?

**Comment by resouer** [comment]
@ryanzhang-oss This field doesn't need to present if:
1. the workload is not podspecable, 
2. the workload is podspecable but assume 'template.spec' as pod spec field path.

**Comment by wonderflow** [comment]
@hongchaodeng  @resouer  `podSpecPath` is better as we already have `workloadRefPath`.


@ryanzhang-oss Yes, it's an optional field as I said in the proposal, it could have following behaviors:

### No label and No `podSpecPath` set

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webservice
spec:
  definitionRef:
    name: podspecworkloads.standard.oam.dev
   ...
```

In this case, we will not do any podSpec specific thing.

### Has label with No  `podSpecPath` set

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webservice
  labels:
     workload.oam.dev/podspecable: true
spec:
  definitionRef:
    name: podspecworkloads.standard.oam.dev
   ...
```

In this case, we will always regard `spec.template.spec` as the `podSpecPath`. This will fit with K8s Deployment/StatefulSet and many other CRD Objects like `OpenKruise CloneSet`/`Knative Service`.

### Has  `podSpecPath` set 

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webservice
  labels:
     workload.oam.dev/podspecable: true
spec:
  podSpecPath: "spec.podSpec"
  definitionRef:
    name: podspecworkloads.standard.oam.dev
   ...
```

In this case, whether there's label or not, we will always make the workload as `podspecable=true`. We will find `podSpecPath` to get the field of podSpec.
