### ISSUE TITLE
[BUG] The "config" attribute is not working for ContainerizedWorkload

### ISSUE THREAD

**Issue by mgianatagh** [crossplane/oam-kubernetes-runtime#235]
**Describe the bug**
The `config` attribute within a container for a ContainerizedWorkload is not working or implemented.

**To Reproduce**
1. Create and apply a Component definition for a ContainerizedWorkload that specifies a config.

For example:
```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: mysql
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "mysql:8.0.20"
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          config:
            - path: /docker-entrypoint-initdb.d/initdb.sql
              value: test
```

2. Create and apply an ApplicationConfiguration using the component.

For example:
```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: mysql
  annotations:
    version: v1.0.0
    description: "test"
spec:
  components:
    - componentName: mysql
```

3. Use `kubectl` to exec into the`mysql` pod and do an `ls /docker-entrypoint-initdb.d/initdb.sql`.  No such file will be found.

**Expected behavior**
I expected to see the file `/docker-entrypoint-initdb.d/initdb.sql` get created in the container and have the contents be `test`.

**Screenshots**

**Cluster information**
```
kubectl version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I searched the code and it did not appear that the fields `Path` and `Value` in the type `ContainerConfigFile` were being used.
