### ISSUE TITLE
Trait apply should use update instead of patch

### ISSUE THREAD

**Issue by hongchaodeng** [crossplane/oam-kubernetes-runtime#272]
## Problem Statement

Currently, when oam-runtime applies traits, it does MergePatch (code [link1](https://github.com/crossplane/crossplane-runtime/blob/378a57303ea0a2d13ae21668044364ad8d1035d9/pkg/resource/api.go#L149) and [link2](https://github.com/kubernetes-sigs/controller-runtime/blob/74fd294a89c65c8efc17ab92e0d2014d36e357a8/pkg/client/patch.go#L100)). Basically, it compares the trait to apply (A), and existing trait object in cache (B), and compare difference between A and B to create a patch to send to APIServer.

This will lead to the following problem:
1. Trait initialized as:
  ```
  auto: false
  rules: [a, b, c]
  ```
2. Trait updated as:
  ```
  auto: true
  ```

In above scenario, we expect `rules` field to be removed, but when we apply it, the trait actually becomes:
```
auto: true
ruels: [a, b, c]
```

## Proposed Solution

To solve the problem, we should just update the spec of trait instead of patch [here](https://github.com/crossplane/oam-kubernetes-runtime/blob/696eb7b021d03865ccdaa74bf5effb207a410ce6/pkg/controller/v1alpha2/applicationconfiguration/apply.go#L98).
For fields safety concerns, the traits are operational data so it will only be managed by OAM platform. Therefore updating is OK in this case. On the contrary, workloads could be changed by end users and we should consider more about how to update it.

**Comment by captainroy-hy** [comment]
Maybe I can help, could you plz assign this issue to me?

**Comment by wonderflow** [comment]
@captainroy-hy  sure, thanks!

**Comment by ryanzhang-oss** [comment]
I wonder why patch can't do "remove"?

**Comment by wonderflow** [comment]
@ryanzhang-oss 'patch' will not remove un-related fields

**Comment by sak0** [comment]
use  APIUpdatingApplicator instead of APIPatchingApplicator
https://github.com/crossplane/crossplane-runtime/blob/v0.10.0/pkg/resource/api.go#L178-L208

crossplane-runtime 0.9.0 -> 0.10.0

**Comment by captainroy-hy** [comment]
> use APIUpdatingApplicator instead of APIPatchingApplicator
> https://github.com/crossplane/crossplane-runtime/blob/v0.10.0/pkg/resource/api.go#L178-L208
> 
> crossplane-runtime 0.9.0 -> 0.10.0

thx for your kindly suggestion!

**Comment by hongchaodeng** [comment]
ref https://github.com/oam-dev/kubevela/issues/876

**Comment by ryanzhang-oss** [comment]
just to be clear, the real problem is not just to remove the fields that are not present in the new CR but also preserve the fields that are not controlled by the trait. 

If this is the real goal then I don't think anyone can solve this unless the trait declares what fields it owns.

**Comment by hongchaodeng** [comment]
@ryanzhang-oss Right.

Let me add another example:
````
# user applies
auto: false
rules: [a, b, c]

# controller adds `others`
auto: false
rules: [a, b, c]
others: "abc"

# user applies again
auto: true

# user wants to see
auto: true
others: "abc"
```

**Comment by hongchaodeng** [comment]
Per our discussion, this is a well known two-way merge problem: https://medium.com/flant-com/3-way-merge-patches-helm-werf-beb7eccecdfe

The correct way to solve this problem is via three-way merge, which is what kubectl apply does. Basically, we need to emulate kubectl apply in the Apply() function -- even though it is called Apply(), it is not yet.

Nowadays k8s supports server side apply which drastically simplifies the client side implementation. Here are some materials I could find related but they only provide examples dispersedly:
- https://github.com/kubernetes/kubernetes/issues/88091
- https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client
- https://ymmt2005.hatenablog.com/entry/2020/04/14/An_example_of_using_dynamic_client_of_k8s.io/client-go#Using-the-dynamic-client-to-implement-SSA
- https://medium.com/swlh/break-down-kubernetes-server-side-apply-5d59f6a14e26

**Comment by captainroy-hy** [comment]
Server-side apply can solve this problem after k8s  v1.19. Before 1.19, it doesn't remove field in such a case shown [here](https://github.com/oam-dev/kubevela/blob/eb9a76c2d1547a0f9668bac5f2582839d8be83a2/pkg/utils/applicator/apply_resource_test.go#L97)

**Comment by wonderflow** [comment]
I'll move this issue to KubeVela, let's discuss it there.

**Comment by hongchaodeng** [comment]
> Before 1.19, it doesn't remove field in such a case shown here

I don't get what the comment said. Could you elaborate more detailedly? And provide an example?

**Comment by allenhaozi** [comment]
> @ryanzhang-oss Right.
> 
> Let me add another example:
> 
> ```
> # user applies
> auto: false
> rules: [a, b, c]
> 
> # controller adds `others`
> auto: false
> rules: [a, b, c]
> others: "abc"
> 
> # user applies again
> auto: true
> 
> # user wants to see
> auto: true
> others: "abc"
> ```
> ```

about this case:

because this resource already exists, so if user want `remove rules`
user should send the following request, 
```
# user applies again
auto: true
rules: null
```
if from patch to update
```
# user update again
auto: true
# result
auto: true
```
this is the semantic of update 

update or patch depends on the business logic of traits.

Is there no uniform standard ?

**Comment by captainroy-hy** [comment]
SS apply this deployment
```yaml
apiVersion: apps/v1
kind: Deployment
...
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
```
SS apply below with the same field manager
```yaml
apiVersion: apps/v1
kind: Deployment
...
spec:
  # replicas: 3 <===== unset
  template:
    spec:
      containers:
      - name: nginx
        # image: nginx:1.14.2 <===== unset
```
In api-server v1.19, we will get 
```yaml
apiVersion: apps/v1
kind: Deployment
...
spec:
  replicas: 1 # <===== reset to default value
  template:
    spec:
      containers:
      - name: nginx
        # image: nginx:1.14.2 # <===== removed because it has no default value
```
But in api-server v1.16-v1.18, we will get
```yaml
apiVersion: apps/v1
kind: Deployment
...
spec:
  replicas: 3 # <===== unchanged
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2 # <===== unchanged
```
Related to this [fix](https://github.com/kubernetes/kubernetes/pull/92661) merged into k8s v1.19
