### ISSUE TITLE
Should not update workload if only revisionEnabled trait was added first time

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#282]
## Reproduce:

Use the example in `examples/component-versioning/`, firstly do not use trait:

```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig-rollout
spec:
  components:
    - componentName: example-component
```

```
$ kubectl get containerizedworkloads.core.oam.dev
NAME                AGE
example-component   11s
```

Then update the appconfig only add a trait:

```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig-rollout
spec:
  components:
    - componentName: example-component
      traits:
        - trait:
            apiVersion: extend.oam.dev/v1alpha2
            kind: SimpleRolloutTrait
            spec:
              replica: 6
              maxUnavailable: 2
              batch: 2
```

The new workload created and the old was reaped.

```
$ kubectl get containerizedworkloads.core.oam.dev
NAME                   AGE
example-component-v1   5s
```

## What was expected?

1.  if only rollout trait was attached without any component change, the workload should not update at all.
2. when new component come, the workload should use name `example-component-v2` and as the mechanism work, the `example-component` workload should be alive.
