### ISSUE TITLE
[Feature] ContainerConfigFile support subPath

### ISSUE THREAD

**Issue by allenhaozi** [crossplane/oam-kubernetes-runtime#285]
When we use ConfigFile internally, we need a scenario for subPath, which requires a field to explicitly express the semantics of subPath

Like the following code

```
// A ContainerConfigFile specifies a configuration file that should be written
// within a container.
type ContainerConfigFile struct {
	// Path within the container at which the configuration file should be
	// written.
	Path string `json:"path"`

        // Path within the volume from which the container's volume should be mounted.
	// Defaults to "" (volume's root).
	// +optional
	SubPath string `json:"subPath,omitempty"`

	// Value that should be written to the configuration file.
	// +optional
	Value *string `json:"value,omitempty"`

	// FromSecret is a secret key reference which can be used to assign a value
	// to be written to the configuration file at the given path in the
	// container.
	// +optional
	FromSecret *SecretKeySelector `json:"fromSecret,omitempty"`
}
```

**Comment by captainroy-hy** [comment]
Currently, ContainerConfigFile only supports ConfigMap and Secret volume source. Without the support of other volumes, such as PersistenVolume, `SubPath` may don't make sense at this moment. 
Q: May I consider your requirement as PersistentVolume instead of just only `SubPath`?

BTW, as for ConfigMap, showing in this [example](https://github.com/crossplane/oam-kubernetes-runtime/blob/09203f4b9a4f8dc14c965eb711b9e9bd1d6a1472/examples/containerized-workload/sample_component.yaml#L20), the controller will create a ConfigMap as below to fulfill ConfigFile
```yaml
apiVersion: v1
data:
  config: test # item name is the last part of splitted Path by "/"; value is from Value field.
kind: ConfigMap
metadata:
  name: example-component-wordpress-1582584990
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
...
```
Afterward, mount it as volume:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: example-component-576f66c9c5-bxbkw
  namespace: default
  ...
spec:
  containers:
  - env:
    - name: TEST_ENV
      value: test
    image: wordpress:latest
    imagePullPolicy: IfNotPresent
    name: wordpress
    ports:
    - containerPort: 80
      name: wordpress
      protocol: TCP
    volumeMounts:
    - mountPath: /test/configfile/
      name: example-component-wordpress-1582584990
    - mountPath: /test/secretconfig
      name: mysecret
    ...
  volumes:
  - configMap:
      defaultMode: 420
      name: example-component-wordpress-1582584990
    name: example-component-wordpress-1582584990
  - name: mysecret
    secret:
      defaultMode: 420
      items:
      - key: password
        path: password
      secretName: mysecret

```

**Comment by allenhaozi** [comment]
This is a deployment of a production environment,
I need to upgrade it to OAM Component
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: elf-bundled
  name: elf-bundled
spec:
  template:
    spec:
      containers:
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: config-nginx-conf
          subPath: nginx.conf
        - mountPath: /www/html/extra_static/t/hadoop.config.html
          name: config-nginx-conf
          subPath: hadoop.config.html
        workingDir: /opt/work
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: hadoop.config.html
            path: hadoop.config.html
          name: elf-bundled-config-nginx-conf
        name: config-nginx-conf
```
