### ISSUE TITLE
[Feature] Make local development more enjoyable 

### ISSUE THREAD

**Issue by zzxwill** [crossplane/oam-kubernetes-runtime#311]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to deploy my code modification to **a real Kubernetes cluster** for further verification. Here is what I used to do.

- Write code

- Generate manifests (if necessary)
```
make manifests
```

- Apply code change
1) Build the image
```
docker build
```

2) Push the image
Push the image to a repository where you have been granted write authority.

3) Modify the chart
Change the image information including `image.repository` and `image.tag` in the chart `charts/oam-kubernetes-runtime`.
```
# values.yaml

# Default values for oam-kubernetes-runtime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
useWebhook: false
image:
  repository: YOUR_REPO/oam-kubernetes-runtime
  tag: THE_TAG_YOU_JUST_BUILT
  pullPolicy: Always
```

4) Delete the old release (if any) and install the chart again
```
helm install charts/oam-kubernetes-runtime
```

5) Do your test

More important, if the test failed, I have to repeat all above again and again and again and again.

**Describe the solution you'd like**

Google [Skaffold](https://skaffold.dev/) is the silver-bullet. All I need is to focus on my code and Skaffold will detect the code and manifests change, deliver the change to the real Kubernetes cluster.

Here is what we need to do.

- Prepare Skaffold configuration file and modify `charts/oam-kubernetes-runtime/templates/oam-controller.yaml`
Normally `skaffold init` will generate the file `skaffold.yaml` automatically, but for delivering Helm chart, it's a little different. 
```
apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: oam-kubernetes-runtime
build:
  artifacts:
    - image: zzxwill/oam-kubernetes-runtime
deploy:
  helm:
    releases:
      - name: core-runtime
        namespace: oam-system
        # create namespace
        createNamespace: true
        # the path of the target chart
        chartPath: ./charts/oam-kubernetes-runtime
        # to override .Values.image
        artifactOverrides:
          imageName: zzxwill/oam-kubernetes-runtime

        valuesFiles:
          - ./charts/oam-kubernetes-runtime/values-skaffold.yaml
```

The modification on `charts/oam-kubernetes-runtime/templates/oam-controller.yaml` is simple.
```
diff --git a/charts/oam-kubernetes-runtime/templates/oam-controller.yaml b/charts/oam-kubernetes-runtime/templates/oam-controller.yaml
index 32c1903..5eb1926 100644
--- a/charts/oam-kubernetes-runtime/templates/oam-controller.yaml
+++ b/charts/oam-kubernetes-runtime/templates/oam-controller.yaml
@@ -156,7 +156,7 @@ spec:
             - "--webhook-port={{ .Values.webhookService.port }}"
             - "--webhook-cert-dir={{ .Values.certificate.mountPath }}"
             {{ end }}
-          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
+          image: {{ .Values.imageName }}
           imagePullPolicy: {{ quote .Values.image.pullPolicy }}
           resources:
             {{- toYaml .Values.resources | nindent 12 }}
```

- run `skaffold dev`
It will automatically build the image, install the chart.
```
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/crossplane/oam-kubernetes-runtime git:(feature-trait-conflicts) ✗ skaffold dev
WARN[0000] starting gRPC server on port 50052. (50051 is already in use)
WARN[0000] starting gRPC HTTP server on port 50053. (50052 is already in use)
Listing files to watch...
 - zzxwill/oam-kubernetes-runtime
Generating tags...
 - zzxwill/oam-kubernetes-runtime -> zzxwill/oam-kubernetes-runtime:v0.0.1-354-g4862b07-dirty
Checking cache...
 - zzxwill/oam-kubernetes-runtime: Found Remotely
Tags used in deployment:
 - zzxwill/oam-kubernetes-runtime -> zzxwill/oam-kubernetes-runtime:v0.0.1-354-g4862b07-dirty@sha256:c82f06cfac4b490d7ed7dac4a83dc0e9bb9d2224a455df9d4d31a755e28e083f
Starting deploy...
Helm release core-runtime not installed. Installing...
NAME: core-runtime
LAST DEPLOYED: Wed Nov 25 00:11:40 2020
NAMESPACE: oam-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for deployments to stabilize...
 - oam-system:deployment/oam-kubernetes-runtime-core-runtime is ready.
Deployments stabilized in 4.441760451s
Press Ctrl+C to exit
Watching for changes...
[core-runtime] I1124 16:11:51.315056       1 request.go:621] Throttling request took 1.034385084s, request: GET:https://172.21.0.1:443/apis/standard.oam.dev/v1alpha1?timeout=32s
[core-runtime] 2020-11-24T16:11:51.475Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
[core-runtime] 2020-11-24T16:11:51.475Z	INFO	oam-kubernetes-runtime	starting the controller manager
[core-runtime] I1124 16:11:51.475843       1 leaderelection.go:242] attempting to acquire leader lease  oam-system/oam-kubernetes-runtime...
[core-runtime] 2020-11-24T16:11:51.476Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
```

- Write you code
Skaffold will automatically detect the code change and redeploy it to the cluster.
Of course, if API changes, `make manifests` is also needed.

For example, I changed file `pkg/controller/v1alpha2/applicationconfiguration/apply.go`, Skaffold will detect the change and automatically do the redploy.
```
[core-runtime] 2020-11-24T16:13:09.012Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"HealthScope","namespace":"default","name":"testapp-default-health","uid":"3fd97f3f-15fb-4ef6-ad48-bd4f2c6fcfb6","apiVersion":"core.oam.dev/v1alpha2","resourceVersion":"9940114"}, "reason": "HealthCheck", "message": "Successfully ran health check"}
Generating tags...
 - zzxwill/oam-kubernetes-runtime -> zzxwill/oam-kubernetes-runtime:v0.0.1-354-g4862b07-dirty
Checking cache...
 - zzxwill/oam-kubernetes-runtime: Not found. Building
Building [zzxwill/oam-kubernetes-runtime]...
Sending build context to Docker daemon  725.5kB
Step 1/14 : FROM golang:1.13 as builder
 ---> d6f3656320fe
Step 2/14 : WORKDIR /workspace
 ---> Running in daafd6144d13
 ---> 82b186772be7
Step 3/14 : COPY go.mod go.mod
 ---> ef50e2e1e4fa
Step 4/14 : COPY go.sum go.sum
 ---> 1e26a1ce3324
Step 5/14 : RUN go mod download
 ---> Running in e408035e6d51
```

- Do the test.

All I have to do is the code itself.

**Describe alternatives you've considered**

Most of the time `go run cmd/oam-kubernetes-runtime/main.go` will do the same thing. But for tests in a real Kubernetes Cluster, it won't apply for it.

**Additional context**

Using Skaffold to make local development more enjoyable could be a guide, but also it could be the recommended way to build image and install the chart. 

Your feedback is highly appreciated.
