### ISSUE TITLE
Improve how ApplicationConfig controller fill in the spec.workloadRef

### ISSUE THREAD

**Issue by ryanzhang-oss** [crossplane/oam-kubernetes-runtime#32]
ApplicationConfig controller should only fills the workload GVK to a `trait` CR if its CRD has a "spec.workloadRef" field conforms to the OAM definition like below
```yaml
    workloadRef:
         properties:
           apiVersion:
             type: string
           kind:
             type: string
           name:
             type: string
         required:
         - apiVersion
         - kind
         - name
         type: object
```

Currently,  ApplicationConfig just blindly adds a key-value pair to a `trait` as an unstructured object. This approach doesn't hurt when the CRD of the trait doesn't have the spec.workloadRef field. However, it will result in rejection from K8s api-server  if the trait CRD already has the spec.workloadRef field but has a different format. It will also cause failure if the CRD doesn't have a spec field. We need a way to check ahead instead of blindly apply
