### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xishengcai** [crossplane/oam-kubernetes-runtime#322]
**Describe the bug**
once component set command, can't remove.

**To Reproduce**
1. component set cmd , example
```
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
        - name: wordpress
          image: wordpress:4.6.1-apache
          command:
            - sleep
            - '10000'
            - 
```

2. apply  component and application
3. remove command
4. check deployment

**Expected behavior**
![image](https://user-images.githubusercontent.com/21197150/110764701-54868100-828e-11eb-8030-a0251803fee6.png)

**Cluster information**
- Kubernetes Version 1.17
