### ISSUE TITLE
Can not create appconfig when "instance-name" parameter removed

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#34]
Now the oam-k8s-runtime need to specify instance-name parameter and pass it to workload CR.

```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
        - name: wordpress
          image: wordpress:4.6.1-apache
          # TODO(negz): Allow environment variables to be set from a secret? OAM
          # doesn't have a concept of Kubernetes secrets, so we will likely need
          # to abstract this somehow.
          ports:
            - containerPort: 80
              name: wordpress
  parameters:
    - name: instance-name
      required: true
      fieldPaths:
        - metadata.name
```

If not give `instance-name` as parameter, the workload CR will fail to create.

```
2020-06-01T19:50:56.978+0800	DEBUG	oam kubernetes runtime example	Cannot apply components	{"controller": "oam/applicationconfiguration.core.oam.dev", "request": "default/example-appconfig", "uid": "19c9bb8f-6889-4c06-853a-7dfd0d16e57c", "version": "6200267", "error": "cannot apply workload \"\": cannot get object: resource name may not be empty",
```

I think we can have a default name.
