### ISSUE TITLE
Use label to replace workloadRef

### ISSUE THREAD

**Issue by resouer** [crossplane/oam-kubernetes-runtime#4]
Since a Trait CR 1:1 maps to Workload CR, maybe we can consider using label/annotation to replace `trait.workloadRef`?

e.g.

```yaml

apiVersion: core.oam.dev/v1alpha2
kind: ManualScalerTrait
metadata:
  labels:
    core.oam.dev/workload: core.oam.dev/v1alpha2.ContainerizedWorkload
    core.oam.dev/workloadName: foo
```

The benefit is as Trait could also be brought by user, we don't want to require user modify CRD before using Crossplane.

(Optional) The link can also be `Component` if we agree on `Component` won't be shared in https://github.com/oam-dev/spec/issues/350.

/cc @negz @ryanzhang-oss

**Comment by resouer** [comment]
(Optional) I am also thinking we can use labels to track the bi-directional links between dev facing objects (Component/Workload) with ops facing objects (Trait/Scope).

**Comment by negz** [comment]
I think it's more common to use references to track one-to-one relationships than labels, which are typically used to track one-to-many relationships. It seems like the rationale here is more about not imposing requirements on the schema of a trait CR than because labels are inherently more appropriate for this case than references. Could you illustrate some cases in which we might want to use an existing, OAM-unaware Kubernetes CR as an OAM trait?

**Comment by resouer** [comment]
@negz Yes, happy to illustrate.

In the wild, many Operators are "Workload + Trait" style by natural. For instance, backup capability of etcd-operator: 

Workload:

 ```yaml 
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "example-etcd-cluster"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: "3.2.13"
```
Trait:

```yaml
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster-backup
spec:
  etcdEndpoints: [<etcd-cluster-endpoints>]
  storageType: S3
  s3:
    # The format of "path" must be: "<s3-bucket-name>/<path-to-backup-file>"
    # e.g: "mybucket/etcd.backup"
    path: <full-s3-path>
    awsSecret: <aws-secret>
```
Similar patterns also exist in serverless solutions such as [knative configuration + route](https://knative.dev/docs/serving/spec/knative-api-specification-1.0/#route).

Also, with the community begin to focus on application centric, many existing capabilities are re-designed as higher level abstractions (decoupled from underlying workload) so they can be used directly as OAM trait, for example [Ingress v2 API](https://kubernetes-sigs.github.io/service-apis/security-model/).

These patterns may not be the majority for now but I think it's a trend that we can consider support at day 0 by loose the enforcement on CRD.
