### ISSUE TITLE
"spec.workloadRef" should not be added to all traits

### ISSUE THREAD

**Issue by zzxwill** [crossplane/oam-kubernetes-runtime#40]
If trying to apply Knative `routes` to workload `configuration`, I hit the issue.
```
$ k describe applicationconfiguration.core.oam.dev/knative-appconfig
Status:
  Conditions:
    Last Transition Time:  2020-06-10T07:49:04Z
    Message:               cannot apply components: cannot apply trait "blue-green-demo": cannot create object: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "workloadRef"
    Reason:                Encountered an error during resource reconciliation
    Status:                False
    Type:                  Synced
  Workloads:
    Component Name:  knative-configuration
    Workload Ref:
      API Version:  serving.knative.dev/v1
      Kind:         Configuration
      Name:         blue-green-demo
Events:
  Type     Reason                 Age                  From                                       Message
  ----     ------                 ----                 ----                                       -------
  Warning  CannotApplyComponents  47m                  oam/applicationconfiguration.core.oam.dev  cannot apply trait "blue-green-demo": cannot create object: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "workloadRef"
```
"spec.workloadRef" can be patched to `manualscalertraits`, but it might now be applicable to other traits.

**Comment by wonderflow** [comment]
@zzxwill will help fix it, thanks

**Comment by wonderflow** [comment]
seems duplicated with #32

**Comment by zzxwill** [comment]
@ryanzhang-oss Here are the steps to reproduce the issue.
# Prerequisites
Install [Knative](https://knative.dev/v0.14-docs/install/any-kubernetes-cluster/) and OAM runtime.
# Deploy Knative routes by ApplicationConfiguration.
## Step 1: deploy Knative Configuration workload with Component
```
k apply -f configuration-component.yaml
component.core.oam.dev/knative-configuration created

cat configuration-component.yaml
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: knative-configuration
spec:
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Configuration
    metadata:
      name: blue-green-demo
      namespace: default
    spec:
      template:
        spec:
          containers:
            - image: gcr.io/knative-samples/knative-route-demo:blue # The URL to the sample app docker image
              env:
                - name: T_VERSION
                  value: "blue"
```
## Step 2: Apply ApplicationConfiguration
```
✗ k apply -f applicationconfiguration-1-deploy-orignal-knative-configuration.yaml
applicationconfiguration.core.oam.dev/knative-appconfig created

✗ cat applicationconfiguration-1-deploy-orignal-knative-configuration.yaml
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: knative-appconfig
spec:
  components:
    - componentName: knative-configuration
    
 ✗ k get configuration
NAME              LATESTCREATED           LATESTREADY             READY   REASON
blue-green-demo   blue-green-demo-txpln   blue-green-demo-txpln   True
```

## Step 3: Deploy Knative routes with Applicationconfiguration

```
✗ cat applicationconfiguration-2-blue.yaml
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: knative-appconfig
spec:
  components:
    - componentName: knative-configuration
      traits:
        - trait:
            apiVersion: serving.knative.dev/v1
            kind: Route
            metadata:
              name: blue-green-demo # The name of our route; appears in the URL to access the app
              namespace: default # The namespace we're working in; also appears in the URL to access the app
            spec:
              traffic:
                - revisionName: blue-green-demo-ltb85
                  percent: 100 # All traffic goes to this revision
```
Then I hit the issue.
```
✗ k edit applicationconfiguration.core.oam.dev/knative-appconfig

'cannot apply components: cannot apply trait "blue-green-demo": cannot
      create object: admission webhook "webhook.serving.knative.dev" denied the request:
      mutation failed: cannot decode incoming new object: json: unknown field "workloadRef"'
```
![image](https://user-images.githubusercontent.com/2805315/84338422-8b7c1900-abce-11ea-818b-cbdf54ab19b4.png)

# What will happen if I barely deploy Knative configuration and routes
With configruation and route manifest as below.
```
apiVersion: serving.knative.dev/v1
kind: Configuration
metadata:
  name: blue-green-demo
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/knative-route-demo:blue # The URL to the sample app docker image
          env:
            - name: T_VERSION
              value: "blue"
```

```
apiVersion: serving.knative.dev/v1
kind: Route
metadata:
  name: blue-green-demo # The name of our route; appears in the URL to access the app
  namespace: default # The namespace we're working in; also appears in the URL to access the app
spec:
  traffic:
    - revisionName: blue-green-demo-lcfrd
      percent: 100 # All traffic goes to this revision
```

I can see the route list.
```
✗ k get routes
NAME              URL                                          READY   REASON
blue-green-demo   http://blue-green-demo.default.example.com   True
```
```

**Comment by ryanzhang-oss** [comment]
Good catch, the Knative actually has an admission controller. It is normally fine to add a field not in the CRD but it's a different story when there is a strict admission controller

**Comment by zzxwill** [comment]
@ryanzhang-oss For the rbac manifest.
```
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/oam-demos/knative git:(master) ✗ cat clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oam-knative-clusterrole
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - configurations
  - routes
  verbs:
  - "*"
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/oam-demos/knative git:(master) ✗ cat clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oam-knative
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oam-knative-clusterrole
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:serviceaccount:crossplane-system:crossplane
```
