### ISSUE TITLE
Knative validation.webhook.serving.knative.dev denied requests for unknown fields from Component

### ISSUE THREAD

**Issue by zzxwill** [crossplane/oam-kubernetes-runtime#47]
Follow similar steps as issue #40
# Prerequisites
Install [Knative](https://knative.dev/v0.14-docs/install/any-kubernetes-cluster/) and OAM runtime.

# Deploy Knative Configuration by ApplicationConfiguration.
## Step 1: deploy Knative Configuration workload with Component
```
✗ cat configuration-component-blue.yaml
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: knative-configuration
spec:
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Configuration
    metadata:
      name: blue-green-demo
      namespace: default
    spec:
      template:
        spec:
          containers:
            - image: gcr.io/knative-samples/knative-route-demo:blue # The URL to the sample app docker image
              env:
                - name: T_VERSION
                  value: "blue"
              ports:
                - containerPort: 80
                  name: wordpress


✗ k apply -f configuration-component-blue.yaml
component.core.oam.dev/knative-configuration created
```
## Step 2: Apply ApplicationConfiguration
```
✗ cat applicationconfiguration-1-deploy-knative-configuration.yaml
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: knative-appconfig
spec:
  components:
    - componentName: knative-configuration


✗ k apply -f applicationconfiguration-1-deploy-knative-configuration.yaml
applicationconfiguration.core.oam.dev/knative-appconfig created

✗ k describe applicationconfiguration.core.oam.dev/knative-appconfig
Name:         knative-appconfig
Namespace:    default
Labels:       <none>
Annotations:  API Version:  core.oam.dev/v1alpha2
Kind:         ApplicationConfiguration
Metadata:
  Creation Timestamp:  2020-06-17T15:27:35Z
  Generation:          1
  Resource Version:    1150849944
  Self Link:           /apis/core.oam.dev/v1alpha2/namespaces/default/applicationconfigurations/knative-appconfig
  UID:                 3b128c22-e1ba-402c-bfa7-81e3f267077a
Spec:
  Components:
    Component Name:  knative-configuration
Status:
  Conditions:
    Last Transition Time:  2020-06-17T15:27:35Z
    Message:               cannot apply components: cannot apply workload "blue-green-demo": cannot create object: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: Port name wordpress is not allowed: spec.template.spec.containers[0].ports
Name must be empty, or one of: 'h2c', 'http1'
    Reason:  Encountered an error during resource reconciliation
    Status:  False
    Type:    Synced
Events:
  Type     Reason                 Age                From                                       Message
  ----     ------                 ----               ----                                       -------
  Normal   RenderedComponents     18s (x3 over 24s)  oam/applicationconfiguration.core.oam.dev  Successfully rendered components
  Warning  CannotApplyComponents  18s (x3 over 24s)  oam/applicationconfiguration.core.oam.dev  cannot apply workload "blue-green-demo": cannot create object: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: Port name wordpress is not allowed: spec.template.spec.containers[0].ports
Name must be empty, or one of: 'h2c', 'http1'
  Normal   RenderedComponents     12s (x2 over 14s)  oam/applicationconfiguration.core.oam.dev  Successfully rendered components
  Warning  CannotApplyComponents  12s (x2 over 13s)  oam/applicationconfiguration.core.oam.dev  cannot apply workload "blue-green-demo": cannot create object: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: Port name wordpress is not allowed: spec.template.spec.containers[0].ports
Name must be empty, or one of: 'h2c', 'http1'

```

If trying to deploy Configuration workload, it will hit a similar issue as above.
```
cannot apply workload "wordpress": cannot create object: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "containers"


✗ cat component-knative-configuration-wordpress.yaml
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: wordpress
spec:
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Configuration
    metadata:
      name: wordpress
      namespace: default
    spec:
      template:
        spec:
          containers:
            - image: wordpress:php7.4-apache
              name: wordpress
              env:
                - name: WORDPRESS_DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: host
                - name: WORDPRESS_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: user
                - name: WORDPRESS_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: password
              ports:
                - containerPort: 80
                  name: wordpress
  parameters:
    - name: db-secret
      description: Secret from which to read PostgreSQL connection details.
      required: true
      fieldPaths:
        - spec.containers[0].env[0].valueFrom.secretKeyRef.name
        - spec.containers[0].env[1].valueFrom.secretKeyRef.name
        - spec.containers[0].env[2].valueFrom.secretKeyRef.name
```

# What will happen if I barely deploy Knative configuration and routes
Pure Knative Configuration deployment will also hit the same issue.
```
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/oam-demos/knative/official git:(master) ✗ k apply -f blue-green-demo-config.yaml
Error from server (BadRequest): error when creating "blue-green-demo-config.yaml": admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: Port name wordpress is not allowed: spec.template.spec.containers[0].ports
Name must be empty, or one of: 'h2c', 'http1'
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/oam-demos/knative/official git:(master) ✗ cat blue-green-demo-config.yaml
apiVersion: serving.knative.dev/v1
kind: Configuration
metadata:
  name: blue-green-demo
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/knative-route-demo:blue # The URL to the sample app docker image
          env:
            - name: T_VERSION
              value: "blue"
          ports:
            - containerPort: 80
              name: wordpress
```

_Originally posted by @zzxwill in https://github.com/crossplane/oam-kubernetes-runtime/issues/40#issuecomment-642369515_
