### ISSUE TITLE
[Design Proposal] Add a generic mechanism for traits to work with workloads in OAM runtime

### ISSUE THREAD

**Issue by ryanzhang-oss** [crossplane/oam-kubernetes-runtime#59]
### Problem
Traits and workloads are two major types of resources in OAM.  Traits usually affect how a workload operate either directly (through spec change) or indirectly (add ingress or sidecar). However, the current OAM implementation does not contain a generic mechanism for traits to locate and apply the desired changes to the resources. Therefore, we propose to address this problem in the OAM Kubernetes runtime.

### Design principles
Before we lay out the detailed design.  Let's first state the overall design objections.
1. We want to design an extensible mechanism that allows a `trait` to apply to any eligible `workload`. This means that this mechanism allows a trait developer to write the controller code once and the controller will work for any new `workloads` that this `trait` can apply to in the future.  

2. The mechanism cannot put any limit on the `trait` or `workload` CRDs. This means that we cannot pre-define any common CRD fields beyond Kubernetes conventions. This is because we want to accommodate any existing CRD to be imported as `workload` or `trait`. 

### Mechanism explained in detail
Here is the step by step workflow
1.  Add a `childResources` field in the  WorkloadDefinition. 
Currently, a workloadDefinition is nothing but a shim of a real workload CRD. We propose to add an **optional** field called `childResources` to the spec of the workloadDefinition. We encourage workload owners to fill in this field when they register their controllers to the OAM system. In this way, they can declare the types of the Kubernetes resources the workload controller actually generates.  For example,
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
   name: schema.example.oam.dev
spec:
  definitionRef:
     name: schema.example.oam.dev
  childResources:
     - groupVersion: apps/v1
       kind: deployment
     - groupVersion: core/v1
       kind: service      
```

2.  ApplicationConfig controller add labels containing the workload information to the emitted trait CR.  For example,
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: ManualScalerTrait
metadata:
  labels:
    core.oam.dev/workloadGroupVersion: core.oam.dev/v1alpha2
    core.oam.dev/workloadKind:  ContainerizedWorkload
    core.oam.dev/workloadName: foo
```

3.  The trait controller can use the following stps in the Reconcile logic to find out all the resources that it should try to modify.

-  Fetch the corresponding `workload` instance by combining the label fields following Kubernetes convention (gvk)
- Fetch the corresponding `workloadDefinition` following an OAM convention that the name of the `workloadDefinition` CR is the name of the `workload` CRD it refers to. For example, the name of the `workloadDefinition` CR that refers to a `containerizedworkloads.core.oam.dev` CRD is exactly `containerizedworkloads.core.oam.dev` as well.
- Fetch all the `childResources` from the corresponding workloadDefinition CR. 
- List each child resource by its type and filter by owner reference. Here, we assume that all the child resources that the workload generates have an owner reference field pointing back to the workload instance.
- Apply the trait-specific logic to the eligible child resources

4. The OAM Kubernetes runtime will provide a helper function to facilitate this process. 

5. The mechanism is entirely optional to accommodate traits that have their own specific logic.
