### ISSUE TITLE
HealthScope

### ISSUE THREAD

**Issue by artursouza** [crossplane/oam-kubernetes-runtime#61]
# Context

Parent Issue: crossplane/crossplane#1480 

[HealthScope](https://github.com/oam-dev/spec/blob/master/standard/scopes/health_scope.md) aggregates the health status of multiple components via a web API.

In Rudr, it was implemented as described here: https://github.com/oam-dev/rudr/tree/master/healthscope

# Proposal

Re-implement Rudr's approach but for the new v1alpha2 spec.

1. Deploy OAM's health scope controller:
```
helm install healthscope ./charts/healthscope
```

```
export POD_NAME=$(kubectl get pods -l "app.kubernetes.io/name=healthscope,app.kubernetes.io/instance=healthscope" -o jsonpath="{.items[0].metadata.name}")
kubectl port-forward $POD_NAME 8080:80
```

The health scope controller (like in Rudr) does 2 things:
1. Periodically check health status of components and update the HealthScope resource status.
2. serve as a http server, to output aggregated health information.

Optionally, it can be extended to offer `/metrics` API so health status can be exported to Prometheus.

2. Instantiate HealthScope as per the v1alpha2 spec:
```
apiVersion: core.oam.dev/v1alpha2
kind: HealthScope
metadata:
  name: example-health-scope
spec:
  probe-method: GET
  probe-endpoint: /health
```

```
$ kubectl get healthscope
NAME              AGE
example-health-scope   31s
```
HealthScope controller keeps track of the healthscopes created.

3. Declare one ApplicationConfiguration, using the health-scope:
```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: first-app
spec:
  components:
    - componentName: helloworld-python-v1
      parameterValues:
        - name: target
          value: Rudr
        - name: port
          value: "9999"
      scopes:
        - apiVersion: core.oam.dev/v1alpha2
           kind: HealthScope
           name: example-health-scope
```

Services generated as part of the ApplicationConfig have the following additional label:
```
healthscope.core.oam.dev/example-health-scope: true
```

Example:
```
$ k describe service helloworld-python-v1
Name:                     helloworld-python-v1
Namespace:                default
Labels:                   workload.oam.crossplane.io=2df4035f-8019-4600-9317-ffbf2ac409b0
                            healthscope.core.oam.dev/example-health-scope: true
Annotations:            <none>
Selector:                 containerizedworkload.oam.crossplane.io=2df4035f-8019-4600-9317-ffbf2ac409b0
Type:                     LoadBalancer
IP:                       10.97.248.231
Port:                     helloworld-python-v1  3003/TCP
TargetPort:               3003/TCP
NodePort:                 helloworld-python-v1  31919/TCP
Endpoints:                172.17.0.12:3003,172.17.0.13:3003
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

HealthScope controller can now query for all services in a health scope by selecting them based on label.

Finally, the health of the scope is reported in:

http://localhost:8080/scopes/example-health-scope

The spec for HealthScope might need to change to incorporate other components, like a database. That work is out of scope (ta dan) for this issue.
