### ISSUE TITLE
Support list/slic type of user defined workloadRef path

### ISSUE THREAD

**Issue by zzxwill** [crossplane/oam-kubernetes-runtime#64]
Workload will be applied to trait CR to its path `spec.workloadRef` in proposal [trait-workload-interaction-mechanism](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/design/one-pager-trait-workload-interaction-mechanism.md#proposal). If the path mechanism support user defined list/slic type `spec.gateways[0]` as below?
```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: bookinfo
spec:
  components:
    - componentName: bookinfo-gateway
      traits:
        - trait:
            apiVersion: networking.istio.io/v1alpha3
            kind: VirtualService
            metadata:
              name: bookinfo
            spec:
              hosts:
              - "*"
              gateways:
              - bookinfo-gateway
```
For more detailed info, please refer to https://github.com/oam-dev/catalog/pull/37
