### ISSUE TITLE
Do not assume that a scope has a workloadRef field

### ISSUE THREAD

**Issue by ryanzhang-oss** [crossplane/oam-kubernetes-runtime#69]
AppConfig now hardcode the workloadRef field on a scope CR. We need to use the same mechanism as trait to know the workloads it is associated with.

**Comment by wonderflow** [comment]
I think this is also a good first issue. Someone who want to take this issue could follow [mechanism in trait](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/design/one-pager-trait-workload-interaction-mechanism.md#proposal).

1. Write a proposal to notice there is a `workloadRefPath` in scopeDefinition.

```
  apiVersion: core.oam.dev/v1alpha2
  kind: ScopeDefinition
  metadata:
    name: healthscopes.core.oam.dev
  spec:
    workloadRefPath: spec.workloadRef
    definitionRef:
      name: healthscopes.core.oam.dev
```

2. Change the hardcode part in oam-k8s-runtime.
