### ISSUE TITLE
Implement Category Scope which can mark annotation/label for workload

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#76]
# Background

In some cases workload will need to mark flags, for example to declare different environments, different tenants, different categories etc.

In OAM world, Application Scopes are very proper for doing so, we can use one scope to indicate some kind of environment. Then component which in this scope will be marked in this environment.

Before OAM exist, most of these demands are implemented by annotation or label of K8s Object. So I propose we implement category scope to uniform control label/annotation mark.

# Proposal 

Implement Category Scope to control label/annotation mark, the controller need be implemented using K8s webhook. So it can mutate workload CR before they are active in K8s cluster.

Assuming we already have this category scope implemented, the workflow would be like below.

1. Create CategoryScope, we can write it directly or reference a key from Secret/Configmap/ObjectField.

```
apiVersion: core.oam.dev/v1alpha2
kind: CategoryScope
metadata:
  name: scope1
spec:
  annotation:
    - key: tenant.uid
       value: "123"
    - key: alibabacloud.vpc
       value: "vpc-2ze"
  labels:
     - key: run.environment
        value: production
     - key: category.key
        valueFrom:
           secretKey:
              name: my-category
              key: categoryname       
```

2. Create AppConfig using this scope

```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: cmp1
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    spec:
       containers: 
         - image: nginx:v1
---
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: app1
spec:
  components:
     - componentName: cmp1
       scopes:
          - scope:
               apiVersion: core.oam.dev/v1alpha2
               kind: CategoryScope
               name: scope1
```

3. Category Scope CR updated and Workload CR created

```
apiVersion: core.oam.dev/v1alpha2
kind: CategoryScope
metadata:
  name: scope1
spec:
  workloadRef:
    - apiVersion: apps/v1
       kind: Deployment
       name: cmp1
  annotation:
    - key: tenant.uid
       value: "123"
    ... 
```

Before workload real created, webhook controller of CategoryScope should mutate and add annotation into it. 

```
    apiVersion: apps/v1
    kind: Deployment
    metadata:
       name: cmp1
# ---------> data injected by webhook start <------------ #
       annotation:
          tenant.uid: "123"
          alibabacloud.vpc: "vpc-2ze"   
       labels:
         run.environment: "production"
         category.key: "ABC"
# ---------> data injected by webhook end  <------------ #
    spec:
       containers: 
         - image: nginx:v1
```

## Problems

In current oam-runtime, the workload created and scope updated at the same time, so we can't ensure webhook will work before workload CR created by oam-runtime.

![image](https://user-images.githubusercontent.com/2173670/86343066-0777f700-bc8b-11ea-96c7-b351c2a6b030.png)

## Solution: Add flag in ScopeDefinition

To ensure webhook controller will definitely work before workload CR created, oam-runtime should have a mechanism to hold creation of workload CR until scope CR marked `completed`.

```
apiVersion: core.oam.dev/v1alpha2
kind: ScopeDefinition
metadata:
  name: categoryscopes.core.oam.dev
spec:
  allowComponentOverlap: true
  definitionRef:
    name: categoryscopes.core.oam.dev
  completeCondition:
     - op: eq
        value: running
        fieldPath: "status.state"
     - op: observed
        fieldPath: "status.observedGeneration"
```

1. observed is compare fieldPath `status.observedGeneration` with `metadata.generation`, they should be equal if update was observed. This is a normal K8s way to indicate object is received by controller.
2. eq is compare value with fieldPath `status.state`.
3. Different conditions are AND-ed together.

**Comment by hongchaodeng** [comment]
Note: use objectSelector to filter workloads

https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector

**Comment by hongchaodeng** [comment]
Here is a summary of the latest solution discussed with @wonderflow 

Assuming an AppConfig containing a Workload _W_ and a Scope _S_, where the W belongs to S.

1. When reconciling AppConfig, OAM Runtime will Apply W and S where W contains a label `scope.oam.dev` pointing to S identifier.
2. A webhook controller, configured with matching rules that check `scope.oam.dev` label exists, will intercept W until having recocniled S and inject S information/business logic into the annotation of W.

**Comment by zzxwill** [comment]
@hongchaodeng Nice, it's a simpler solution. Will the label of W look like below?
```
apiVersion: core.oam.dev/v1alpha2
kind: W
metadata:
  name: cmp1
  labels:
    scope.oam.dev: scope1.CategoryScope.core.oam.dev
```
