### ISSUE TITLE
Don't block if traitDefinition or workloadDefinition not exist

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#82]
Now oam-k8s-runtime will check traitDefinition(for revisionAware) andworkloadDefinition(for workloadRef), but if these definition file not exist, application deploy will fail. However, the trait or workload can work without these information, so we shouldn't require definition files MUST exist. 

In fact, we can automatically generate a basic definition file for those workload/trait, or we can regard there's one. Then the deploy won't fail.

For example, for ingress trait as below:

```
...
      traits:
        - trait:
            apiVersion: extensions/v1beta1
            kind: Ingress
            metadata:
              name: tracker-ingress
            spec:
                backend:
                  serviceName: web-ui
                  servicePort: 8080 
```

If we don't have a traitdefinition, we can assume it's a basic one like below:

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: ingresses.extensions
spec:
  definitionRef:
    name: ingresses.extensions 
```

All the information can be automatically generated. The main idea is to not block a normal deploy.
