### ISSUE TITLE
The dag does not support two input dependencies

### ISSUE THREAD

**Issue by jack0liu** [crossplane/oam-kubernetes-runtime#89]
The dependency like below, when one component input parameter( ex. db-host) ready , then *apiserver2* will been created, but another parameter(monitor-host) not been paved.

```yaml
 - componentName: apiserver2
      dataInputs:
        - valueFrom:
            dataOutputName: monitor-host
          toFieldPaths:
            - "spec.containers[0].env[0].value"
        - valueFrom:
            dataOutputName: db-host
          toFieldPaths:
            - "spec.containers[0].env[1].value"
```
