### ISSUE TITLE
add observedGeneration to represent Component and AppConfig has reconciled

### ISSUE THREAD

**Issue by wonderflow** [crossplane/oam-kubernetes-runtime#91]
`observedGeneration` field of status in K8s object is widely used in K8s built-in resource. It reflects the generation of the most recently observed Object.

With the help of `observedGeneration` field, user can recognize whether a CR is reconciled by controller.

A workflow will like below:

```
apiversion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: c1
  generation: 1
spec:
  workload:
    image: nginx:v1
    ...
```

After the controller reconciled, the `observedGeneration` will appear and align with `generation` in metadata:

```
apiversion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: c1
  generation: 1
spec:
  workload:
    image: nginx:v1
    ...
status:
  observedGeneration: 1
```

Later, we have another change, it will be:

```
apiversion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: c1
  generation: 2
spec:
  workload:
    image: nginx:v2
    ...
status:
  observedGeneration: 1
```

And after reconciled, it will be:

```
apiversion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: c1
  generation: 2
spec:
  workload:
    image: nginx:v2
    ...
status:
  observedGeneration: 2
```

Also, CR of AppConfig also need to add this field.
